#!/usr/bin/env python3

import argparse, socket, time, json, select, struct, math

#DEBUG = True
DEBUG = False

parser = argparse.ArgumentParser(description='route packets')
parser.add_argument('asn', type=int, help="AS Number")
parser.add_argument('networks', metavar='networks', type=str, nargs='+', help="networks")
args = parser.parse_args()

##########################################################################################

# Message Fields
TYPE = "type"
SRCE = "src"
DEST = "dst"
MESG = "msg"
TABL = "table"

# Message Types
DATA = "data"
DUMP = "dump"
UPDT = "update"
RVKE = "revoke"
NRTE = "no route"

# Update Message Fields
NTWK = "network"
NMSK = "netmask"
ORIG = "origin"
LPRF = "localpref"
APTH = "ASPath"
SORG = "selfOrigin"

# internal route info
CUST = "cust"
PEER = "peer"
PROV = "prov"

# received incoming data
messages = []
forwarding_table = []

##########################################################################################

# UTILITY FUNCTIONS
# convert ip address to binary representation of four 8-bit segments
def binl(ip):   
    ipl = ip.split(".")
    binl = []
    for n in ipl:
        # turn into binary
        binip = bin(int(n))[2:]
        # add padding for 8-bit segments
        strip = str(binip).zfill(8)
        binl.append(strip)
    return binl 

# calculate the combination for network/netmask addresses
def combine_submask(netmask_ip, dest_ip):
    print("OG Netmask: ", netmask_ip)
    print("OG Dest: ", dest_ip)
    combined = []
    # separate bits into four groups of 8-bits
    for b in range(4):
        # calculate bitwise and for each bit individually
        finpart = ""
        for s in range(8):
            finpart += str(int(netmask_ip[b][s]) & int(dest_ip[b][s]))
        print("Part: ", finpart)
        combined.append(finpart)
    print("Combined: ", combined)
    return combined

# match combined network/netmask addresses with corresponding neighbor network
def mask(dest):
    result = []
    # fake = ["192.168.0.0"]
    for e in forwarding_table:
        nmbinl = binl(e['netmask'])
        destbinl = binl(dest)
        # Test variables
        # nmbinl = binl("192.168.0.0")
        # destbinl = binl("255.255.255.0")
        subresult = combine_submask(nmbinl, destbinl)
        result.append(subresult)
    return result


class Router:

    routes = None
    updates = None
    relations = None
    sockets = None

    def __init__(self, networks):
        self.routes = []
        self.updates = []
        self.relations = {}
        self.sockets = {}
        for relationship in networks:
            # ip address and type (customer, provider, peer)
            network, relation = relationship.split("-")
            if DEBUG: 
                print("Starting socket for", network, relation)
            self.sockets[network] = socket.socket(socket.AF_UNIX, socket.SOCK_SEQPACKET)
            self.sockets[network].setblocking(0)
            self.sockets[network].connect(network)
            self.relations[network] = relation
        return
           
    def lookup_routes(self, daddr):
        """ Lookup all valid routes for an address """
        # TODO
        outroutes = []
        return outroutes

    def get_shortest_as_path(self, routes):
        """ select the route with the shortest AS Path """
        # TODO
        outroutes = []
        return outroutes
            
    def get_highest_preference(self, routes):
        """ select the route with the shortest AS Path """
        # TODO
        outroutes = []
        return outroutes
         
    def get_self_origin(self, routes):
        """ select self originating routes """
        # TODO
        outroutes = []
        return outroutes

    def get_origin_routes(self, routes):
        """ select origin routes: EGP > IGP > UNK """
        # TODO
        outroutes = []
        return outroutes

    def filter_relationships(self, srcif, routes):
        """ Don't allow Peer->Peer, Peer->Prov, or Prov->Peer forwards """
        outroutes = []
        return outroutes

    def get_route(self, srcif, daddr):
        """	Select the best route for a given address	"""
        # TODO
        peer = None
        routes = lookup_routers(daddr)
        # Rules go here
        if routes:
            # 1. Highest Preference
            routes = self.get_highest_preference(routes)
            # 2. Self Origin
            routes = self.get_self_origin(routes)
            # 3. Shortest ASPath
            routes = self.get_shortest_as_path(routes)
            # 4. EGP > IGP > UNK
            routes = self.get_origin_routes(routes)
            # 5. Lowest IP Address
            # TODO
            # Final check: enforce peering relationships
            routes = self.filter_relationships(srcif, routes)
        return self.sockets[peer] if peer else None

    def forward(self, srcif, packet):
        """	Forward a data packet	"""
        port = mask(packet['dst'])
        # Scenario 1: no route
        # Scenario 2: one possible route
        # Scenario 3: multiple possible routes
        # Scenario 4: tie breaker needed
        return False

    def coalesce(self):
        """	coalesce any routes that are right next to each other	"""
        # TODO (this is the most difficult task, save until last)
        return False

    def update(self, srcif, packet):
        """	handle update packets	"""
        # adds entry to forwarding table (updates)
        entry = {"network": packet['msg']['network'], "netmask": packet['msg']['netmask'], "peer": packet['src']}
        
        forwarding_table.append(entry)
        self.updates.append(packet)
        announcement = {"type": "update", "src": "", "dst": "", "msg": {"network": packet['msg']['network'], "netmask": packet['msg']['netmask'], "localpref": packet['msg']['localpref'], "ASPath": [], "origin": packet['msg']['origin'], "selfOrigin": packet['msg']['selfOrigin']}}
        for a in packet['msg']['ASPath']:
            announcement['msg']['ASPath'].append(a)
        
        announcement['msg']['ASPath'].append(args.asn)    
        print("PACKET: ", packet)
        for n in self.sockets.keys():
            if packet['src'] != n:
                # creates appropriate python address for announcement source
                dest = '.'.join(n.split('.')[:-1]+["1"])
                # sets the correct values for announcement src, dst, and ancts
                announcement['src'] = dest
                announcement['dst'] = n
                print("ANNOUNCEMENT: ", announcement)
                ancts = json.dumps(announcement)
                anctb = ancts.encode('utf-8')
                self.sockets[n].sendall(anctb)
        
        print("Updates: ", self.updates)
        print("Entry: ", entry)
        return False
    
    def revoke(self, packet):
        """	handle revoke packets	"""
        # TODO
        return True

    def dump(self, packet):
        """	handles dump table requests	"""
        # TODO
        return True

    def handle_packet(self, srcif, packet):
        """	dispatches a packet """
        # TODO
        return False

    def send_error(self, conn, msg):
        """ Send a no_route error message """
        # TODO
        return

    def run(self):
        while True:
            # opens and listens to Unix domain sockets
            socks = select.select(self.sockets.values(), [], [], 0.1)[0]
            for conn in socks:
                try:
                    k = conn.recv(65535)
                except:
                    # either died on a connection reset, or was SIGTERM's by parent
                    return
                if k:
                    for sock in self.sockets:
                        if self.sockets[sock] == conn:
                            # source interface: source port/socket of data message
                            srcif = sock
                    msg = json.loads(k)
                    message = {"type": msg['type'], "dst": msg['dst'], "src": msg['src'], "msg": msg['msg']}
                    messages.append(message)
                    
                    if message['type'] == 'update':
                        self.update(srcif, msg)
                    if message['type'] == 'data':
                        self.forward(srcif, msg)
                    if not self.handle_packet(srcif, msg):
                        self.send_error(conn, msg)
                else:
                    return
                print(messages)
        return

if __name__ == "__main__":
    router = Router(args.networks)
    router.run()
